# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiuApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiuApp
  pod 'SwiftLint'

  target 'LiuAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiuAppUITests' do
    # Pods for testing
  end

end
